[package]
name = "drsplayer"
version = "0.1.0"
authors = ["Markus Ast <m@rkusa.st>"]
edition = "2018"

[dependencies]
hlua51 = { git = "https://github.com/rkusa/hlua51.git" }
lua51-sys = { git = "https://github.com/rkusa/hlua51.git" }
libc = "0.2"
regex = "1"
log = "0.4"
log4rs = "0.8"
const-cstr = "0.1"
byteorder = "1.2"
uuid = "0.6"
serde = "1.0"
serde_json = "1.0"
serde_derive = " 1.0"
base64 = "0.9"
reqwest = "0.8"
either = "1.5"
audiopus = "0.1"
hound = "3.4"